### ISSUE TITLE
El dólar oficial no actualiza

### ISSUE THREAD

**Issue by z72diego** [es-js/esjs#2]
Va 60 pesos atrasado!

Saludos!

**Comment by enzonotario** [comment]
Hola @z72diego, este repositorio es de EsJS, no de DolarApi.com, por lo que no deberíamos discutir de dólares aquí.

Sin embargo, respecto a lo que mencionas, la API sólo expone los valores de la Fuente de Datos. Si la Fuente de Datos está desactualizada, o es errónea, es algo que debe reportarse/corregirse desde la Fuente de Datos; no desde la API.

Puedes ver más sobre esto [aquí](https://github.com/enzonotario/esjs-dolar-api/issues/4) y [aquí](https://github.com/enzonotario/esjs-dolar-api/issues/8). Si tienes más dudas, por favor dirígete al [Repositorio de DolarApi.com](https://github.com/enzonotario/esjs-dolar-api).

Saludos!

**Comment by z72diego** [comment]
Hola. Ok. No hay problema. Una API que vincule a https://www.ambito.com/contenidos/dolar-html sin dudas sería más confiable. Saludos!

**Comment by enzonotario** [comment]
Perfecto, será tenido en cuenta. Cuando lo implemente te informaré en el Repositorio de DolarApi.com.

Gracias, saludos!
